---
version: "3"
services:
    node:
        image: "becodeorg/node"
        environment:
            NODE_ENV: "development"
        volumes:
            - "./package.json:/src/app/package.json"
            - "./node_modules:/src/app/node_modules"
            - "./bin:/src/app/bin"
        expose:
            - "12345"
            - "9229"
        ports:
            - "80:12345"
            - "9229"
        command: "nodemon --inspect=0.0.0.0:9229 --watch bin/server bin/server/index.js"
    postgres:
        image: "postgres"
        restart: "unless-stopped"
        ports:
            - "5432:5432"
        volumes:
            - "postgres_db:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "dev"
            POSTGRES_PASSWORD: "dev"
    pgadmin:
        image: "dpage/pgadmin4"
        ports:
            - "8002:80"
        depends_on:
            - "postgres"
        environment:
            PGADMIN_DEFAULT_EMAIL: "dev@dev.com"
            PGADMIN_DEFAULT_PASSWORD: "dev"
    mailcatcher:
        image: "tophfr/mailcatcher"
        ports:
            - "8004:80"
volumes:
    postgres_db:
